<a href="https://colab.research.google.com/github/JerushaGubbi/CN/blob/main/CIE_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
df=pd.read_csv('/content/mtcars (6) 1.csv')
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,origin
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,6
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,2
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,4
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,6
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,5
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,4
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,3
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,5
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,6
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,7
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,9
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,6
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,7
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,8
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,5
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,4
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,3
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,4
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,5
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,6
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,7
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,9
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,3
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,2
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,4
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,8

In [22]:
df.drop('model',axis=1,inplace=True)

KeyError: "['model'] not found in axis"

In [3]:
df.isnull().sum()

mpg       0
cyl       0
disp      0
hp        0
drat      0
wt        0
qsec      0
vs        0
am        0
gear      0
carb      0
origin    0
dtype: int64

In [17]:
df.fillna(method='ffill')

/tmp/ipython-input-1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb  origin
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4       6
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4       8
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1       9
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1       2
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2       4
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1       6
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4       5
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2       4
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2       2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4       3
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4       4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3       5
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3       6
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3       7
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4       8
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4       9
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4       6
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1       7
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2       8
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1       5
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1       4
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2       3
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2       4
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4       5
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2       6
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1       7
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2       8
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2       9
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4       3
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6       2
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8       4
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2       8

In [5]:
df.isnull().sum()

mpg       0
cyl       0
disp      0
hp        0
drat      0
wt        0
qsec      0
vs        0
am        0
gear      0
carb      0
origin    0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [9]:
x_train

    cyl   disp   hp  drat     wt   qsec  vs
12    8  275.8  180  3.07  3.730  17.60   0
0     6  160.0  110  3.90  2.620  16.46   0
4     8  360.0  175  3.15  3.440  17.02   0
16    8  440.0  230  3.23  5.345  17.42   0
5     6  225.0  105  2.76  3.460  20.22   1
13    8  275.8  180  3.07  3.780  18.00   0
11    8  275.8  180  3.07  4.070  17.40   0
23    8  350.0  245  3.73  3.840  15.41   0
1     6  160.0  110  3.90  2.875  17.02   0
2     4  108.0   93  3.85  2.320  18.61   1
26    4  120.3   91  4.43  2.140  16.70   0
3     6  258.0  110  3.08  3.215  19.44   1
21    8  318.0  150  2.76  3.520  16.87   0
27    4   95.1  113  3.77  1.513  16.90   1
22    8  304.0  150  3.15  3.435  17.30   0
18    4   75.7   52  4.93  1.615  18.52   1
31    4  121.0  109  4.11  2.780  18.60   1
20    4  120.1   97  3.70  2.465  20.01   1
7     4  146.7   62  3.69  3.190  20.00   1
10    6  167.6  123  3.92  3.440  18.90   1
14    8  472.0  205  2.93  5.250  17.98   0
28    8  351.0  264  4.22  3.170  14.50   0
19    4   71.1   65  4.22  1.835  19.90   1
6     8  360.0  245  3.21  3.570  15.84   0

In [10]:
x_test

    cyl   disp   hp  drat     wt   qsec  vs
29    6  145.0  175  3.62  2.770  15.50   0
15    8  460.0  215  3.00  5.424  17.82   0
24    8  400.0  175  3.08  3.845  17.05   0
17    4   78.7   66  4.08  2.200  19.47   1
8     4  140.8   95  3.92  3.150  22.90   1
9     6  167.6  123  3.92  3.440  18.30   1
30    8  301.0  335  3.54  3.570  14.60   0
25    4   79.0   66  4.08  1.935  18.90   1

In [11]:
y_train

     mpg
12  17.3
0   21.0
4   18.7
16  14.7
5   18.1
13  15.2
11  16.4
23  13.3
1   21.0
2   22.8
26  26.0
3   21.4
21  15.5
27  30.4
22  15.2
18  30.4
31  21.4
20  21.5
7   24.4
10  17.8
14  10.4
28  15.8
19  33.9
6   14.3

In [12]:
y_test

     mpg
29  19.7
15  10.4
24  19.2
17  32.4
8   22.8
9   19.2
30  15.0
25  27.3

In [14]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print("y_pred",y_pred)

y_pred [[18.48564947]
 [10.51627729]
 [16.51172223]
 [26.7668298 ]
 [26.28782092]
 [18.61210578]
 [12.19149459]
 [27.36112708]]

In [15]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
rmse = np.sqrt(mse)

In [16]:
print(' Mean squared error', mse)
print(' Mean absolute error', mae)
print(' R2_score', r2)
print(' Rmse',rmse)

 Mean squared error 7.606195634454144
 Mean absolute error 2.0746779272663813
 R2_score 0.8150019303306787
 Rmse 2.7579332179104963